# Generated by Django 4.2.20 on 2025-05-06 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='My Site', max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Short slogan or tagline.', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='About your site, used in footers and SEO.', null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='site/stamp/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number', max_length=100, null=True)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers', max_length=20)),
                ('default_currency', models.CharField(default='INR', help_text='Currency code, e.g., INR, USD', max_length=10)),
                ('bank_details', models.TextField(blank=True, help_text='Bank or UPI info for manual payments', null=True)),
                ('invoice_footer_note', models.TextField(blank=True, help_text='Default note shown in invoice footers', null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SMTPSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('default_from_email', models.EmailField(default='noreply@example.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteLegal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms_of_service', models.TextField()),
                ('privacy_policy', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Site Legal Content',
            },
        ),
    ]
