# Generated by Django 4.2.20 on 2025-05-10 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_alter_invoice_client_delete_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_issued'], 'permissions': [('can_generate_reports', 'Can generate invoice reports'), ('can_export_invoices', 'Can export invoices'), ('can_view_all_invoices', 'Can view all invoices (not just own)')], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Payment',
                'verbose_name_plural': 'Invoice Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('status_change', 'Status Changed'), ('payment', 'Payment Recorded'), ('email_sent', 'Email Sent'), ('reminder_sent', 'Reminder Sent'), ('viewed', 'Viewed by Client'), ('download', 'Downloaded')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='invoices.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Activity Log',
                'verbose_name_plural': 'Invoice Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
